development:
  adapter: postgresql
  database: pe_development
  pool: 5
  username: pe_development

test:
  adapter: postgresql
  database: pe_test
  pool: 5
  username: pe_test

production:
  adapter: postgresql
  database: pe_production
  pool: 5
  username:pe_production
